project:
  type: website

website:
  title: "Home"
  
  navbar:
    
    right:
      - href: overview.qmd
        text: Overview
   

  search:
    location: navbar
    type: textbox

format:
  html:
    theme:
      light: yeti
    css: styles.css
    toc: true

editor: visual
